settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: false # experimental feature, enable only for <5 monitors or on paid plans

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Some Systems Non-Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: scotthelme-ghost-io
    name: scotthelme.ghost.io
    url: 'https://scotthelme.ghost.io/'

  - id: scotthelme-co-uk
    name: scotthelme.co.uk
    url: 'https://scotthelme.co.uk'

  - id: report-uri-com
    name: report-uri.com
    url: 'https://report-uri.com/'

  - id: securityheaders-com
    name: securityheaders.com
    url: 'https://securityheaders.com/'

  - id: crawler-ninja
    name: crawler.ninja
    url: 'https://crawler.ninja/'

  - id: whynohttps-com
    name: whynohttps.com
    url: 'https://whynohttps.com/'

  - id: httpforever-com
    name: httpforever.com
    url: 'http://httpforever.com/'

  - id: pi-hole
    name: doh.scotthelme.co.uk
    url: 'https://doh.scotthelme.co.uk/dns-query?dns=q80BAAABAAAAAAAAA3d3dwdleGFtcGxlA2NvbQAAAQAB'
