settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Some Systems Non-Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: 'Some checks failed'

monitors:
  - id: scotthelme-ghost-io
    name: scotthelme.ghost.io
    url: 'https://scotthelme.ghost.io/'

  - id: scotthelme-co-uk
    name: scotthelme.co.uk
    url: 'https://scotthelme.co.uk'

  - id: report-uri-com
    name: report-uri.com
    url: 'https://report-uri.com/'

  - id: securityheaders-com
    name: securityheaders.com
    url: 'https://securityheaders.com/'

  - id: crawler-ninja
    name: crawler.ninja
    url: 'https://crawler.ninja/'

  - id: why-no-https-com
    name: whynohttps.com
    url: 'https://whynothttps.com/'

  - id: httpforever-com
    name: httpforever.com
    url: 'https://httpforever.com/'